// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgrthafbdhesqyapbskd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndncnRoYWZiZGhlc3F5YXBic2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjE2ODksImV4cCI6MjA1NTc5NzY4OX0.TIHVb3BtN1TMeRQYpwmISiYsK6Yj9V1-vesmp8PXgwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);